# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec314347bcff21eb37bec44e6e7411c5913a19dfeeefccc6e99ca849ee4ccf9a0a733e10800cc19b3917653600f1c1f18d8c7d2b50f31a1236701ac3e3c693ce

test:
  secret_key_base: a6a20219245ba9e50d5d9159a452055ec9c9daf5d6cf031c513aa746b48fe3e0fbade747b710f8791c6ad0c90c89518f8dcbb435b2f2f9894d4f5a342581042b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
